✨ Pull from both sdcards in `phone photos`

diff --git a/phone b/phone
--- a/phone
+++ b/phone
@@ -32,27 +32,32 @@ function fixADB {
 
 
 function getPhotos {
-    dir=$(mktemp --dry-run --directory --tmpdir=. $(date -I)-photos-XXXX)
+    for storage in self/primary 3337-3432; do
+        dir=$(mktemp --dry-run --directory --tmpdir=. $(date -I)-photos-XXXX)
 
-    adb pull sdcard/DCIM/Camera $dir
-    rm $dir/thumbnails &> /dev/null
+        echo "Starting pull of $dir DCIM camera folder …"
+        adb pull /storage/$storage/DCIM/Camera $dir
 
-    if [[ -z $(ls $dir) ]]; then
-        echo "No photos to archive"
-        rm -rf $dir
-    else
-        if adb shell "test -d sdcard/DCIM/Archive"; then
-            echo Archive directory already existed, appending
-        elif adb shell "test \! -e sdcard/DCIM/Archive"; then
-            echo Archive directory did not exist, creating
-            adb shell "mkdir sdcard/DCIM/Archive/"
+        if [[ -z $(ls "$dir") ]]; then
+            echo "No photos to archive"
+            rm -rf "$dir"
         else
-            echo Archive is not a directory, aborting!
-            return 1
+            if adb shell "test -d $storage/DCIM/Archive"; then
+                echo "Archive directory already existed, appending …"
+            elif adb shell "test \! -e $storage/DCIM/Archive"; then
+                echo "Archive directory did not exist, creating …"
+                adb shell "mkdir $storage/DCIM/Archive/"
+            else
+                echo "Archive is not a directory, aborting!"
+                return 1
+            fi
+            echo "Archiving photos on phone…"
+            adb shell "mv $storage/DCIM/Camera/* $storage/DCIM/Archive/"
         fi
-        echo "Archiving photos on phone…"
-        adb shell "mv sdcard/DCIM/Camera/* sdcard/DCIM/Archive/"
-    fi
+
+        echo "Removing local thumbnails …"
+        rm "$dir"/thumbnails &> /dev/null || true
+    done
 }
 
 
